doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                FIND_IN_SET: 'App\DoctrineExtensions\Query\Mysql\FindInSet'
                WEEK: 'App\DoctrineExtensions\Query\Mysql\Week'
                MONTH: 'App\DoctrineExtensions\Query\Mysql\Month'
                DAYOFWEEK: 'App\DoctrineExtensions\Query\Mysql\DayOfWeek'
                CURDATE: 'App\DoctrineExtensions\Query\Mysql\CurDate'
                NOW: 'App\DoctrineExtensions\Query\Mysql\Now'
                DATEFORMAT: 'App\DoctrineExtensions\Query\Mysql\DateFormat'
